In [ ]:
import numpy as np

In [ ]:
p1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p2 = np.arange(0, 12).reshape(3,4)

In [ ]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
p3 = np.arange(0, 27).reshape(3, 3, 3)

In [ ]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in p3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]

In [ ]:
for i in np.nditer(p3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26

In [ ]:
for i in np.nditer(p2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11

In [ ]:
# Reshaping

p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.transpose(p3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# Ravel
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
## Stacking

In [ ]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12, 24).reshape(3, 4)

In [ ]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((w1, w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((w1, w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
## Splitting

np.hsplit(w1, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(w2, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# **Pandas**

In [ ]:
import pandas as pd

In [ ]:
data = pd.Series(["A", "B", "C", "D", "E"])
data

0    A
1    B
2    C
3    D
4    E
dtype: object

In [ ]:
data.dtype

dtype('O')

In [ ]:
data.values

array(['A', 'B', 'C', 'D', 'E'], dtype=object)

In [ ]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
data.name = "Alphabets"
data

0    A
1    B
2    C
3    D
4    E
Name: Alphabets, dtype: object

In [ ]:
data.index = ["Apple", "Banana", "Cherry", "Dog", "Elephant"]
data

Apple       A
Banana      B
Cherry      C
Dog         D
Elephant    E
Name: Alphabets, dtype: object

In [ ]:
print(data.name)

Alphabets

In [ ]:
data["Apple"]

'A'

In [ ]:
data["Apple":"Dog"]

Apple     A
Banana    B
Cherry    C
Dog       D
Name: Alphabets, dtype: object

In [ ]:
data.loc["Elephant"]

'E'

In [ ]:
data.loc[["Apple", "Cherry", "Banana"]]

Apple     A
Cherry    C
Banana    B
Name: Alphabets, dtype: object

In [ ]:
details = pd.Series({
    "name":"Harpreet",
    "Course" : "CSE",
    "Age" : 19,
    "City" : "Hoshiarpur",
    "Hobby" : "Music"
})
details

name        Harpreet
Course           CSE
Age               19
City      Hoshiarpur
Hobby          Music
dtype: object

In [ ]:
details.name = "Details"
details

name        Harpreet
Course           CSE
Age               19
City      Hoshiarpur
Hobby          Music
Name: Details, dtype: object

In [ ]:
details["Hobby"] = "Traveling"
details

name        Harpreet
Course           CSE
Age               19
City      Hoshiarpur
Hobby      Traveling
Name: Details, dtype: object