In [ ]:
import pandas as pd

In [ ]:
data = {
    "fruits":['apple', 'banana', 'mango', 'orange', 'papaya'],
    "colors":['red', 'blue', 'green', 'yellow', 'pink'],
    "numbers":[1, 2, 3, 4, 5],
    "animals":['dog', 'cat', 'bird', 'fish', 'snake']
}

In [ ]:
df = pd.DataFrame(data)
df

   fruits  colors  numbers animals
0   apple     red        1     dog
1  banana    blue        2     cat
2   mango   green        3    bird
3  orange  yellow        4    fish
4  papaya    pink        5   snake

In [ ]:
df.head(3)

   fruits colors  numbers animals
0   apple    red        1     dog
1  banana   blue        2     cat
2   mango  green        3    bird

In [ ]:
df.tail(2)

   fruits  colors  numbers animals
3  orange  yellow        4    fish
4  papaya    pink        5   snake

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   fruits   5 non-null      object
 1   colors   5 non-null      object
 2   numbers  5 non-null      int64
 3   animals  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

        numbers
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [ ]:
df

   fruits  colors  numbers animals
0   apple     red        1     dog
1  banana    blue        2     cat
2   mango   green        3    bird
3  orange  yellow        4    fish
4  papaya    pink        5   snake

In [ ]:
df.iloc[1:3]

   fruits colors  numbers animals
1  banana   blue        2     cat
2   mango  green        3    bird

In [ ]:
df.loc[1:3, ["fruits", "colors"]]

   fruits  colors
1  banana    blue
2   mango   green
3  orange  yellow

In [ ]:
df.drop("fruits", axis = 1)

   colors  numbers animals
0     red        1     dog
1    blue        2     cat
2   green        3    bird
3  yellow        4    fish
4    pink        5   snake

In [ ]:
df

   fruits  colors  numbers animals
0   apple     red        1     dog
1  banana    blue        2     cat
2   mango   green        3    bird
3  orange  yellow        4    fish
4  papaya    pink        5   snake

In [ ]:
df.drop("fruits", axis = 1, inplace = True)

In [ ]:
df

   colors  numbers animals
0     red        1     dog
1    blue        2     cat
2   green        3    bird
3  yellow        4    fish
4    pink        5   snake

In [ ]:
df.shape

(5, 3)

In [ ]:
df.dtypes

colors     object
numbers     int64
animals    object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   colors   5 non-null      object
 1   numbers  5 non-null      int64
 2   animals  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
df.describe()

        numbers
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [ ]:
df["numbers"] = df["numbers"] + 10
df

   colors  numbers animals
0     red       11     dog
1    blue       12     cat
2   green       13    bird
3  yellow       14    fish
4    pink       15   snake

In [ ]:
# renaming column name

df.rename(columns = {"numbers":"num"}, inplace = True)
df

   colors  num animals
0     red   11     dog
1    blue   12     cat
2   green   13    bird
3  yellow   14    fish
4    pink   15   snake

In [ ]:
print(df)

   colors  num animals
0     red   11     dog
1    blue   12     cat
2   green   13    bird
3  yellow   14    fish
4    pink   15   snake